name: Build - MacOS

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    if: github.repository == 'iOSRealRun-cli/iOSRealRun-cli'
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: ${{ matrix.arch }} # optional x64 or arm64, defaults to x64
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true

      - name: Copy Files
        run: |
          mkdir output
          mkdir output/libimobiledevice
          cp build/*.bin output/
          cp config.yaml output/
          cp route.txt output/
          cp main.command output/
          cp -r DeveloperDiskImage output/
          cp -r libimobiledevice/darwin output/libimobiledevice

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iOSRealRun-cli-${{ runner.os }}-${{ matrix.arch }}
          path: |
            output/
